[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "A crate exposing common functions for doing proper error handling in a FFI context."
name = "ffi-helpers"
version = "0.1.0"

[dependencies]
libc = "0.2.33"
